export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';

export const FETCH_NEWS = 'FETCH_NEWS';

export const SET_AUTH = 'SET_AUTH';

export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';

export const SET_AUTH_FAILURE = 'SET_AUTH_FAILURE';